users_index:
    path:     /
    defaults: { _controller: "GoVoyageBundle:users:index" }
    methods:  GET

users_show:
    path:     /{idUser}/show
    defaults: { _controller: "GoVoyageBundle:users:show" }
    methods:  GET

users_new:
    path:     /new
    defaults: { _controller: "GoVoyageBundle:users:new" }
    methods:  [GET, POST]

users_edit:
    path:     /{idUser}/edit
    defaults: { _controller: "GoVoyageBundle:users:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{idUser}/delete
    defaults: { _controller: "GoVoyageBundle:users:delete" }
    methods:  DELETE
