go_voyage_users:
    resource: "@GoVoyageBundle/Resources/config/routing/users.yml"
    prefix:   /users

go_voyage_vol:
    resource: "@GoVoyageBundle/Resources/config/routing/vol.yml"
    prefix:   /vol

go_voyage_demande:
    resource: "@GoVoyageBundle/Resources/config/routing/demande.yml"
    prefix:   /demande

go_voyage_homepage:
    path:     /trial
    defaults: { _controller: GoVoyageBundle:Default:index }
